### PR TITLE
Use size_t for array or vector index

### PR DESCRIPTION
**Pull request by killoctal**

### CODE REVIEW

**Comment by pjohnmeyer** [comment]
I need to do some local testing but this looks good so far. @charlesnicholson do you remember any reason why these were `int` instead of `size_t`? Unfortunately I don't believe I have any way of seeing the old svn logs.

**Comment by charlesnicholson** [comment]
I think when we wrote it we didn't know what size_t was. :(

This looks good, I think it should go in!

**Comment by killoctal** [comment]
I did this for fix warnings when I use CHECK_ARRAY_* on a vector.
Maybe I missed some but I think there is the minimum requested :)

**Comment by pjohnmeyer** [comment]
There are many other places where an `int` today could be something unsigned like size_t, but it looks to me that you caught everything on the interface that had to do with array / vector sizes. Merging. Thanks!

**Pull request merged**
