### PR TITLE
Run tests/suites using custom selection from command line

### PR DESCRIPTION
**Pull request by killoctal**
**Commands:**
- _--test_ One or multiple test names to execute, can be combined with _--suite_
- _--suite_ One or multiple suite names to execute, can be combined with _--test_

**Special feature:** You do not have to specify explicitely --test and --suite, you
can mix suite names and test names and the cmd will find the way. The
constraint is that it must have no arguments beginning with --.
For disabling this feature, set allowImplicitArgs=false

**Usage examples:**
Explicit :
 _myTests.exe --suite MySuite1 MyOtherSuite --test MySpecialTest MyOtherTest_
Implicit :
 _myTests.exe MySpecialTest MyOtherTest MySuite1_

### CODE REVIEW

**Comment by killoctal** [comment]
Damned, problem with VS 2008 again

**Comment by killoctal** [comment]
Did you have time for checking this ? Thanks ;)

**Comment by killoctal** [comment]
Oops, wrong button I closed pull request

**Comment by pjohnmeyer** [comment]
Sorry for the long delay; I have looked but I have not reviewed in detail. Would be happy to see others' opinions.

**Comment by killoctal** [comment]
Any news ? Thanks

**Comment by killoctal** [comment]
Hi Patrick,
Did you take a decision about this pull request ?
Thank you :)

**Comment by pjohnmeyer** [comment]
It might be just me, but I feel that this pull is just too big for what it is adding.

In a previous pull request [I suggested starting small](https://github.com/unittest-cpp/unittest-cpp/pull/124#issuecomment-242895102), and I'd like to stick to that.

**Comment by killoctal** [comment]
It adds 3 new classes (SuitePredicate, ArgumentsReader, PredicateCmdBuilder) and make minor changes to existing files. The 30% of the code is for testing the feature.

Not that big for me since it is a complete feature and can evolute, more arguments could be added in the future (with the parameterized tests for example). Arguments reading is a nightmare if you don't use a parser.

I could have written the code shortly but I think it is time to write some "clean code" instead of keeping the using "C" way-to-do legacy, what do you think ?

Thanks

**Comment by grahamreeds** [comment]
Depends if "clean code" breaks people who are stuck using gcc 4.8.4 on
Ubuntu 14_04 LTS...

**Comment by pjohnmeyer** [comment]
Sorry, @killoctal, but I'm going to stick to my guns here. Let's [start small as I suggested](https://github.com/unittest-cpp/unittest-cpp/pull/124#issuecomment-242895102) and just add support for running one suite, explicitly, using `--suite <suiteName>`. We can work our way up to adding more features to this new function, in small increments. It will take more back-and-forth but I think we'll be happier with the outcome, and we'll likely get higher quality feedback too.

**Pull request closed without merging**
