### PR TITLE
Make formatting more consistent

### PR DESCRIPTION
**Pull request by pjohnmeyer**
This still isn't perfect, but I threw together a quick uncrustify configuration that did most of the work, and then hand-tweaked a few things as well. Three-space indentation, no more tabs. Some of this will likely change later when I develop the contributing guidelines.

### CODE REVIEW

**Comment by grahamreeds** [comment]
Three spaces? Why three?

**Comment by pjohnmeyer** [comment]
I rolled a d20 and that's what came up. *That* was a nervous moment, let me tell you. :)

In other words, I picked a rule so that it would be _something_.

**Comment by hymerman** [comment]
"19 spaces?! Nooooooooo!"

I can personally only remember one other project using 3 spaces in the last 10 years - Graham's right, it is a bit weird :)

**Comment by pjohnmeyer** [comment]
I used it for half of my career, when I was still doing C++ in my day job. I'm okay with being weird.

    ¯\_(ツ)_/¯

**Pull request merged**
