### PR TITLE
Feature msvc clang

### PR DESCRIPTION
**Pull request by GabrielHare**
UnitTest++ supports clang as a compiler for Visual Studio via native extension

For information on enabling & using the extension see:
https://blogs.msdn.microsoft.com/vcblog/2015/12/04/clang-with-microsoft-codegen-in-vs-2015-update-1/
(Since that post, an update offers v140_clang_c2)
And, for instruction for CMake see:
https://github.com/boostorg/hana/wiki/Setting-up-Clang-on-Windows

However, the CMakeLists.txt for UnitTest++ uses the MSVC variable to test for the compiler type, which will be incorrect when clang is used.

This PR uses a test against the compiler name instead. It has been verified with:
- cmake 3.7.0 (Windows)
- clang 3.8.0 (v140_clang_c2 Visual Studio 2015)
- msvc 19.0.24215.1 (Visual Studio 2015)
- cmake 3.5.2 (Ubuntu)
- GCC 6.2.0 (Ubuntu)
- clang 3.8.1 (Ubuntu)
- cmake 3.4.3 (Apple)
- AppleClang 8.0.0 generated for XCode
- AppleClang 8.0.0 generated for command line make

NOTE: It is also possible to attempt to install and use LLVM & Clang, but the compiler flags are a mess
http://releases.llvm.org/download.html
http://clang.llvm.org/docs/MSVCCompatibility.html

### CODE REVIEW

**Comment by grahamreeds** [comment]
Don't like this. I am using an old version of Ubuntu that is LTS and that
is using CMake 2.8.12.2.

GR

**Comment by GabrielHare** [comment]
@grahamreeds Makes sense, and I see the error in Travis - I'll fix & update.

**Comment by GabrielHare** [comment]
@grahamreeds update passes tests now - I hope you'll support this PR

**Comment by pjohnmeyer** [comment]
Your changes made me notice the portion of the CMake message that reads "Please use a different C++ compiler." That message is misleading; compilers that don't support C++11 still work with UnitTest++.

As such I don't consider this a warning; please change the new and existing message to STATUS level, and while you're at it I'd be pleased if you removed that sentence.

**Comment by GabrielHare** [comment]
Thank you for taking a look at this.
Your requested changes appear to elevate the message level from STATUS to WARNING and do not remove the statement that the a different compiler should be used.
I'm happy to make your requested changes (as I understand them) or accept the changes - please clarify what your would prefer.

(Also, please note that this PR removes the building of TestUnitTest++ from "all" target.)

**Comment by grahamreeds** [comment]
Why do you remove building of the unit tests from the all target?

GR

**Comment by GabrielHare** [comment]
Actually, that's not in this PR - I can open another with that (and CI changes).

**Comment by grahamreeds** [comment]
But why do you think it is beneficial to remove building of unittests from
the all target? You are supposed to run unittests after every build...

**Comment by GabrielHare** [comment]
In my case I'm using UnitTest++ in my project via CMake's [ExternalProject_Add](https://cmake.org/cmake/help/v3.7/module/ExternalProject.html) so for each complete rebuild of the project I'm also rebuilding UnitTest++, and would be rebuilding TestUnitTest++ if it were not excluded.

I'm guessing that I'm not unusual in building UnitTest++ when building a project.

**Comment by pjohnmeyer** [comment]
> Actually, that's not in this PR - I can open another with that (and CI changes).

You can already skip building and running TestUnitTest++ by setting the CMake build option `UTPP_INCLUDE_TESTS_IN_BUILD` to `OFF`, so the secondary pull request won't be necessary.

**Comment by GabrielHare** [comment]
@pjohnmeyer thank you for the cmake flag hint.

**Comment by GabrielHare** [comment]
@pjohnmeyer do the changes made in 0b15459 work for you?

**Comment by GabrielHare** [comment]
Just got the notification - thank you :-)

**Pull request merged**
